#pragma once

#define SLIPSTREAM_RENDER_API_VERSION 1

#define SLIPSTREAM_RENDER_MAX_SWAPCHAIN_BUFFERS 3

#define SLIPSTREAM_RENDER_ALL_REMAINING_MIP_LEVELS 0xFFFFFFFF
#define SLIPSTREAM_RENDER_ALL_REMAINING_ARRAY_SLICES 0xFFFFFFFF
